engineStrict: true

linkWorkspacePackages: true

managePackageManagerVersions: true

minimumReleaseAgeExclude:
  - next
  - react
  - react-dom
  - '@next/*'

nodeVersion: 24.14.0

onlyBuiltDependencies: []

overrides:
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'

packageManagerStrictVersion: true

preferFrozenLockfile: true

preferWorkspacePackages: true

registrySupportsTimeField: false

resolutionMode: time-based

saveWorkspaceProtocol: rolling

sharedWorkspaceLockfile: false

strictDepBuilds: true

updateNotifier: false

useNodeVersion: 24.14.0

verifyDepsBeforeRun: install
