/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IframeRouteImport } from "./routes/iframe"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ApiTestrunRouteImport } from "./routes/api/testrun"
import { Route as ApiTestRouteImport } from "./routes/api/test"
import { Route as ApiServiceInfoRouteImport } from "./routes/api/service-info"
import { Route as ApiSandboxResultsRouteImport } from "./routes/api/sandbox-results"
import { Route as ApiPublicSpecRouteImport } from "./routes/api/public-spec"
import { Route as ApiModelSolutionRouteImport } from "./routes/api/model-solution"
import { Route as ApiGradeRouteImport } from "./routes/api/grade"
import { Route as ApiExtractStubRouteImport } from "./routes/api/extract-stub"
import { Route as ApiStatusUpRouteImport } from "./routes/api/status/up"

const IframeRoute = IframeRouteImport.update({
  id: "/iframe",
  path: "/iframe",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestrunRoute = ApiTestrunRouteImport.update({
  id: "/api/testrun",
  path: "/api/testrun",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: "/api/test",
  path: "/api/test",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServiceInfoRoute = ApiServiceInfoRouteImport.update({
  id: "/api/service-info",
  path: "/api/service-info",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSandboxResultsRoute = ApiSandboxResultsRouteImport.update({
  id: "/api/sandbox-results",
  path: "/api/sandbox-results",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSpecRoute = ApiPublicSpecRouteImport.update({
  id: "/api/public-spec",
  path: "/api/public-spec",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelSolutionRoute = ApiModelSolutionRouteImport.update({
  id: "/api/model-solution",
  path: "/api/model-solution",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGradeRoute = ApiGradeRouteImport.update({
  id: "/api/grade",
  path: "/api/grade",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractStubRoute = ApiExtractStubRouteImport.update({
  id: "/api/extract-stub",
  path: "/api/extract-stub",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusUpRoute = ApiStatusUpRouteImport.update({
  id: "/api/status/up",
  path: "/api/status/up",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/iframe": typeof IframeRoute
  "/api/extract-stub": typeof ApiExtractStubRoute
  "/api/grade": typeof ApiGradeRoute
  "/api/model-solution": typeof ApiModelSolutionRoute
  "/api/public-spec": typeof ApiPublicSpecRoute
  "/api/sandbox-results": typeof ApiSandboxResultsRoute
  "/api/service-info": typeof ApiServiceInfoRoute
  "/api/test": typeof ApiTestRoute
  "/api/testrun": typeof ApiTestrunRoute
  "/api/status/up": typeof ApiStatusUpRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/iframe": typeof IframeRoute
  "/api/extract-stub": typeof ApiExtractStubRoute
  "/api/grade": typeof ApiGradeRoute
  "/api/model-solution": typeof ApiModelSolutionRoute
  "/api/public-spec": typeof ApiPublicSpecRoute
  "/api/sandbox-results": typeof ApiSandboxResultsRoute
  "/api/service-info": typeof ApiServiceInfoRoute
  "/api/test": typeof ApiTestRoute
  "/api/testrun": typeof ApiTestrunRoute
  "/api/status/up": typeof ApiStatusUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/iframe": typeof IframeRoute
  "/api/extract-stub": typeof ApiExtractStubRoute
  "/api/grade": typeof ApiGradeRoute
  "/api/model-solution": typeof ApiModelSolutionRoute
  "/api/public-spec": typeof ApiPublicSpecRoute
  "/api/sandbox-results": typeof ApiSandboxResultsRoute
  "/api/service-info": typeof ApiServiceInfoRoute
  "/api/test": typeof ApiTestRoute
  "/api/testrun": typeof ApiTestrunRoute
  "/api/status/up": typeof ApiStatusUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/iframe"
    | "/api/extract-stub"
    | "/api/grade"
    | "/api/model-solution"
    | "/api/public-spec"
    | "/api/sandbox-results"
    | "/api/service-info"
    | "/api/test"
    | "/api/testrun"
    | "/api/status/up"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/iframe"
    | "/api/extract-stub"
    | "/api/grade"
    | "/api/model-solution"
    | "/api/public-spec"
    | "/api/sandbox-results"
    | "/api/service-info"
    | "/api/test"
    | "/api/testrun"
    | "/api/status/up"
  id:
    | "__root__"
    | "/"
    | "/iframe"
    | "/api/extract-stub"
    | "/api/grade"
    | "/api/model-solution"
    | "/api/public-spec"
    | "/api/sandbox-results"
    | "/api/service-info"
    | "/api/test"
    | "/api/testrun"
    | "/api/status/up"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IframeRoute: typeof IframeRoute
  ApiExtractStubRoute: typeof ApiExtractStubRoute
  ApiGradeRoute: typeof ApiGradeRoute
  ApiModelSolutionRoute: typeof ApiModelSolutionRoute
  ApiPublicSpecRoute: typeof ApiPublicSpecRoute
  ApiSandboxResultsRoute: typeof ApiSandboxResultsRoute
  ApiServiceInfoRoute: typeof ApiServiceInfoRoute
  ApiTestRoute: typeof ApiTestRoute
  ApiTestrunRoute: typeof ApiTestrunRoute
  ApiStatusUpRoute: typeof ApiStatusUpRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/iframe": {
      id: "/iframe"
      path: "/iframe"
      fullPath: "/iframe"
      preLoaderRoute: typeof IframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/testrun": {
      id: "/api/testrun"
      path: "/api/testrun"
      fullPath: "/api/testrun"
      preLoaderRoute: typeof ApiTestrunRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/test": {
      id: "/api/test"
      path: "/api/test"
      fullPath: "/api/test"
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/service-info": {
      id: "/api/service-info"
      path: "/api/service-info"
      fullPath: "/api/service-info"
      preLoaderRoute: typeof ApiServiceInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/sandbox-results": {
      id: "/api/sandbox-results"
      path: "/api/sandbox-results"
      fullPath: "/api/sandbox-results"
      preLoaderRoute: typeof ApiSandboxResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/public-spec": {
      id: "/api/public-spec"
      path: "/api/public-spec"
      fullPath: "/api/public-spec"
      preLoaderRoute: typeof ApiPublicSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/model-solution": {
      id: "/api/model-solution"
      path: "/api/model-solution"
      fullPath: "/api/model-solution"
      preLoaderRoute: typeof ApiModelSolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/grade": {
      id: "/api/grade"
      path: "/api/grade"
      fullPath: "/api/grade"
      preLoaderRoute: typeof ApiGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/extract-stub": {
      id: "/api/extract-stub"
      path: "/api/extract-stub"
      fullPath: "/api/extract-stub"
      preLoaderRoute: typeof ApiExtractStubRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/status/up": {
      id: "/api/status/up"
      path: "/api/status/up"
      fullPath: "/api/status/up"
      preLoaderRoute: typeof ApiStatusUpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IframeRoute: IframeRoute,
  ApiExtractStubRoute: ApiExtractStubRoute,
  ApiGradeRoute: ApiGradeRoute,
  ApiModelSolutionRoute: ApiModelSolutionRoute,
  ApiPublicSpecRoute: ApiPublicSpecRoute,
  ApiSandboxResultsRoute: ApiSandboxResultsRoute,
  ApiServiceInfoRoute: ApiServiceInfoRoute,
  ApiTestRoute: ApiTestRoute,
  ApiTestrunRoute: ApiTestrunRoute,
  ApiStatusUpRoute: ApiStatusUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
