apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend
spec:
  template:
    spec:
      containers:
        - name: main-frontend
          env:
            - name: PUBLIC_ADDRESS
              value: "https://courses.mooc.fi"
