POST http://project-331.local/api/v0/pages HTTP/1.1
Content-Type: application/json

{
  "content": [
    {
      "clientId": "8af8cd1c-7e5b-4e67-b178-a2c64361f89a",
      "name": "core/paragraph",
      "isValid": true,
      "attributes": {
        "content": "Ever since the birth of computation with Alan Turing, humans have put high hopes on the power of computers and artificial intelligence (AI). AI is expected to bring significant and diverse benefits to society – from greater efficiency and productivity to tackling a number of difficult global problems, such as climate change, poverty, disease, and conflict.",
        "dropCap": false
      },
      "innerBlocks": []
    },
    {
      "clientId": "2f5bfdc4-050d-498a-a794-69ea378f3394",
      "name": "core/paragraph",
      "isValid": true,
      "attributes": {
        "content": "AI technologies shape our societies. They have an enormous impact on our daily lives. At the same time, multiple legal and societal issues have revealed the potential of these technologies to produce undesirable impacts. Algorithms can enhance already existing biases. They can discriminate. They can threaten our security, manipulate us and have lethal consequences.",
        "dropCap": false
      },
      "innerBlocks": []
    },
    {
      "clientId": "b037487e-7b9b-44c5-acdc-a153dca6d56e",
      "name": "core/paragraph",
      "isValid": true,
      "attributes": {
        "content": "For these reasons, people need to explore the ethical, social and legal aspects of AI systems. There is a common call for the ethics of AI – meaning how are we to develop and use this technology in an ethically acceptable and sustainable way? What are the ethical and moral principles we should adopt and follow?",
        "dropCap": false
      },
      "innerBlocks": []
    },
    {
      "clientId": "60b4cee2-eb8d-4e71-bbb0-34085896a47d",
      "name": "core/paragraph",
      "isValid": true,
      "attributes": {
        "content": "In this course, we'll take a look at the ethical issues related to contemporary AI, open up their background in philosophy and give them an interpretation in terms of computer and other sciences. The goal of course is to develop skills for ethical thinking. The course provides a guide – or a roadmap – on the ethically sustainable design, implementation and use of AI. It will introduce you to basic ethical concepts, their theoretical background, and their role in discussion on contemporary AI.",
        "dropCap": false
      },
      "innerBlocks": []
    },
    {
      "clientId": "6cedbbcf-5b00-48e6-ab2b-c054e1b01a49",
      "name": "core/paragraph",
      "isValid": true,
      "attributes": { "content": "", "dropCap": false },
      "innerBlocks": []
    }
  ],
  "url_path": "/chapter-1/1-a-guide-to-ai-ethics",
  "title": "A guide to AI ethics",
  "course_id": "85e8fb6a-4565-49d4-8fc9-6a882f93f052",
  "exercises": []
}


####

PUT http://localhost:3001/api/v0/pages/40ca9bcf-8eaa-41ba-940e-0fd5dd0c3c02 HTTP/1.1
Content-Type: application/json

{
  "content": [{"type": "x"}],
  "url_path": "/part-1/hello-world",
  "title": "Hello world!",
  "exercises": [
    {
      "id": "e5773229-71fc-494e-8619-b26308df74e3",
      "name": "Exercise 11",
      "exercise_items": [
        {
          "id": "3ad208d0-a22a-43e3-a395-6f9972ce873e",
          "exercise_type": "quiz",
          "assignment": [{"type": "y"}],
          "spec": { "has_swag": false }
        }
      ]
    }
  ]
}

####

GET http://localhost:3001/api/v0/pages/40ca9bcf-8eaa-41ba-940e-0fd5dd0c3c02

####

DELETE http://localhost:3001/api/v0/pages/40ca9bcf-8eaa-41ba-940e-0fd5dd0c3c02


###

http://localhost:3001/api/v0/organizations


###

http://localhost:3001/api/v0/courses/10363c5b-82b4-4121-8ef1-bae8fb42a5ce/page-by-path//part-2/hello-world


###

POST http://project-331.local/api/v0/cms/courses HTTP/1.1
Content-Type: application/json

{
    "name": "Introduction to introduction",
    "slug": "introduction-to-introduction",
    "organization_id": "1b89e57e-8b57-42f2-9fed-c7a6736e3eec"
}


###

POST http://project-331.local/api/v0/cms/courses/d86cf910-4d26-40e9-8c9c-1cc35294fdbb/images HTTP/1.1
Content-Type: image/png

BINARY_DATA


#########


GET http://project-331.local/api/v0/files/organizations/1b89e57e-8b57-42f2-9fed-c7a6736e3eec/courses/d86cf910-4d26-40e9-8c9c-1cc35294fdbb/images/nNQbVax81fH4SLCXuQ9NrOWtqfHT6x.jpg
