apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
    - image: headless-lms
      context: headless-lms
      sync:
        manual:
          - src: "**/*.rs"
            dest: "/app"
    - image: cms
      context: cms
      sync:
        manual:
          - src: "src/**/*"
            dest: "/app"
    - image: main-frontend
      context: main-frontend
      sync:
        manual:
          - src: "src/**/*"
            dest: "/app"
    - image: example-exercise
      context: example-exercise
      sync:
        manual:
          - src: "src/**/*"
            dest: "/app"
    - image: course-material
      context: course-material
      sync:
        manual:
          - src: "src/**/*"
            dest: "/app"
  local:
    # Allow parallel builds
    concurrency: 0
deploy:
  kubectl:
    manifests:
      - kubernetes/**/*
      - kubernetes/*
  kubeContext: minikube
portForward:
  - resourceType: statefulset
    resourceName: postgres
    port: 5432
    localPort: 54328
