apiVersion: skaffold/v2beta12
kind: Config
build:
  tagPolicy:
    # sha256 tag policy pushes the latest tag, which is used for caching
    sha256: {}
  artifacts:
    - image: headless-lms
      docker:
        dockerfile: Dockerfile
      context: services/headless-lms
      sync:
        manual:
          - src: "**/*.rs"
            dest: "/app"
          - src: "**/*.sql"
            dest: "/app"
          - src: "shared-module/**/*"
            dest: "/app"
    - image: cms
      context: services/cms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*"
            dest: "/app"
    - image: main-frontend
      context: services/main-frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*"
            dest: "/app"
    - image: example-exercise
      context: services/example-exercise
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*"
            dest: "/app"
    - image: course-material
      context: services/course-material
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*"
            dest: "/app"
    - image: quizzes
      context: services/quizzes
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*"
            dest: "/app"

  local:
    # Allow parallel builds
    concurrency: 0
deploy:
  kustomize:
    paths:
      - kubernetes/dev
  kubeContext: minikube
portForward:
  - resourceType: statefulset
    resourceName: postgres
    namespace: default
    port: 5432
    localPort: 54328
profiles:
  - name: only-db
    patches:
      - op: remove
        path: /build/artifacts
      - op: remove
        path: /deploy/kustomize
    deploy:
      kubectl:
        manifests:
          - kubernetes/dev/postgres-dev.yml
