[package]
name = "mooc-langs-api"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0" # minimum required Rust version, update if you use a new API
license = "Apache-2.0"

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
oauth2 = "4.4.1"
serde = { version = "1.0.163", features = ["derive"] }
thiserror = "1.0.40"
uuid = "1.3.3"
