[package]
name = "mooc-langs-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# Date and time library
chrono = { version = "0.4.31", features = ["serde"] }
# An extensible, strongly-typed implementation of OAuth2
oauth2 = "4.4.2"
# A generic serialization/deserialization framework
serde = { version = "1.0.193", features = ["derive"] }
# A JSON serialization file format
serde_json = "1.0.108"
# derive(Error)
thiserror = "1.0.50"
# A library to generate and parse UUIDs.
uuid = { version = "1.6.1", features = ["serde"] }
