import { defineConfig, UserConfig } from "@hey-api/openapi-ts"

const createConfig = (input: string, path: string) =>
  ({
    input,
    output: {
      clean: true,
      entryFile: false,
      fileName: {
        suffix: ".generated",
      },
      path,
      header: (_ctx) => {
        return [
          "// This file is auto-generated.",
          "// DO NOT EDIT THIS FILE MANUALLY",
          "/* eslint-disable */",
        ]
      },
    },
    plugins: [
      {
        name: "@hey-api/client-fetch",
        throwOnError: true,
      },
      "@hey-api/typescript",
      "zod",
      {
        name: "@hey-api/sdk",
        responseStyle: "data",
        validator: {
          response: "zod",
        },
      },
      "@tanstack/react-query",
    ],
  }) satisfies UserConfig

export default [
  createConfig("../headless-lms/server/openapi/main-frontend.openapi.json", "src/generated/api"),
  createConfig(
    "../headless-lms/server/openapi/course-material.openapi.json",
    "src/generated/course-material-api",
  ),
]
