import { defineConfig, UserConfig } from "@hey-api/openapi-ts"

export default defineConfig({
  input: "../headless-lms/server/openapi/main-frontend.openapi.json",
  output: {
    clean: true,
    entryFile: false,
    fileName: {
      suffix: ".generated",
    },
    path: "src/generated/api",
    header: (_ctx) => {
      return [
        "// This file is auto-generated.",
        "// DO NOT EDIT THIS FILE MANUALLY",
        "/* eslint-disable */",
      ]
    },
  },
  plugins: [
    "@hey-api/typescript",
    "zod",
    {
      name: "@hey-api/sdk",
      responseStyle: "data",
      validator: {
        response: "zod",
      },
    },
    "@tanstack/react-query",
  ],
} satisfies UserConfig)
