# Dependencies for the course material migration scripts.
# Run `bundle install` here (or via bin/migrate-material-and-upload.sh, which uses
# `bundle exec` against this Gemfile) to install them.
source "https://rubygems.org"

gem "rest-client", "~> 2.1"
gem "dotenv", "~> 3.1"
gem "kramdown", "~> 2.4"
