import type { UserConfig } from "@hey-api/openapi-ts"
import path from "path"
import { fileURLToPath } from "url"

if (process.env.GENERATE_BINDINGS_RUN !== "1") {
  throw new Error(
    "Do not run this generator directly. Run bin/generate-bindings from the repo root.",
  )
}

const configDir = import.meta.dirname
const resolveFromConfig = (relativePath: string) => path.resolve(configDir, relativePath)

const createConfig = (input: string, path: string) =>
  ({
    input,
    output: {
      clean: true,
      entryFile: true,
      fileName: {
        suffix: ".generated",
      },
      path,
      header: () => {
        return [
          "// This file is auto-generated by running bin/generate-bindings.",
          "// DO NOT EDIT THIS FILE OR DO NOT UPDATE THIS FILE IN ANY OTHER WAY THAN BY RUNNING bin/generate-bindings.",
          "//",
          "// Since this file is auto-generated, any changes you make to it will be overwritten by the next run of bin/generate-bindings.",
        ]
      },
    },
    plugins: [
      {
        name: "@hey-api/client-fetch",
        throwOnError: true,
      },
      "@hey-api/typescript",
      "zod",
      {
        name: "@hey-api/sdk",
        responseStyle: "data",
        validator: {
          response: "zod",
        },
      },
      "@tanstack/react-query",
    ],
  }) satisfies UserConfig

export default createConfig(
  resolveFromConfig("../../services/headless-lms/server/openapi/cms.openapi.generated.json"),
  resolveFromConfig("../../services/cms/src/generated/api"),
)
