import { UserConfig } from "@hey-api/openapi-ts"

const createConfig = (input: string, path: string) =>
  ({
    input,
    output: {
      clean: true,
      entryFile: true,
      fileName: {
        suffix: ".generated",
      },
      path,
      header: () => {
        return [
          "// This file is auto-generated by running bin/generate-bindings.",
          "// DO NOT EDIT THIS FILE OR DO NOT UPDATE THIS FILE IN ANY OTHER WAY THAN BY RUNNING bin/generate-bindings.",
          "//",
          "// Since this file is auto-generated, any changes you make to it will be overwritten by the next run of bin/generate-bindings.",
          "/* eslint-disable */",
        ]
      },
    },
    plugins: [
      {
        name: "@hey-api/client-fetch",
        throwOnError: true,
      },
      "@hey-api/typescript",
      "zod",
      {
        name: "@hey-api/sdk",
        responseStyle: "data",
        validator: {
          response: "zod",
        },
      },
      "@tanstack/react-query",
    ],
  }) satisfies UserConfig

export default createConfig(
  "services/headless-lms/server/openapi/cms.openapi.generated.json",
  "services/cms/src/generated/api",
)
