import { UserConfig } from "@hey-api/openapi-ts"

export default {
  input: "services/headless-lms/server/openapi/auth.openapi.generated.json",
  output: {
    clean: true,
    entryFile: false,
    fileName: {
      suffix: ".generated",
    },
    path: "shared-module/packages/common/src/generated/auth-api",
    header: () => {
      return [
        "// This file is auto-generated by running bin/generate-bindings.",
        "// DO NOT EDIT THIS FILE OR DO NOT UPDATE THIS FILE IN ANY OTHER WAY THAN BY RUNNING bin/generate-bindings.",
        "//",
        "// Since this file is auto-generated, any changes you make to it will be overwritten by the next run of bin/generate-bindings.",
        "/* eslint-disable */",
      ]
    },
  },
  plugins: [
    {
      name: "@hey-api/client-fetch",
      throwOnError: true,
    },
    "@hey-api/typescript",
    "zod",
    {
      name: "@hey-api/sdk",
      responseStyle: "data",
      validator: {
        response: "zod",
      },
    },
  ],
} satisfies UserConfig
