//! HTTP routes, controllers, middleware, and OpenAPI.
pub mod controllers;
pub mod openapi;
pub mod prelude;
pub use headless_lms_external_service_clients::service_clients;
pub use headless_lms_use_cases::domain;
#[macro_use]
extern crate tracing;
#[macro_use]
extern crate doc_macro;
/// Includes the type's generated docs as a string.
/// generated by doc-file-generator as a string.
/// Used with the helper macro from the doc-macro crate: #[generated_doc]
#[macro_export]
macro_rules! generated_docs {
    ($t: expr_2021, ts) => {
        concat!(
            "## Response TypeScript definition\n",
            "```ts\n",
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/generated-docs/",
                stringify!($t),
                ".ts"
            )),
            "\n```\n",
        )
    };
    ($t: expr_2021, json) => {
        concat!(
            "## Example response\n",
            "```json\n",
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/generated-docs/",
                stringify!($t),
                ".json"
            )),
            "\n```\n",
        )
    };
    ($t: expr_2021) => {
        generated_docs!($t, json)
    };
}
pub use headless_lms_use_cases::OAuthClient;
#[cfg(test)]
pub use headless_lms_use_cases::test_helper;
mod error_macros {
    use headless_lms_use_cases::domain::error::{ControllerError, ControllerErrorType};
    headless_lms_utils::define_err_macro!(
        controller_err,
        ControllerError,
        ControllerErrorType,
        ControllerErrorType,
        "Create an HTTP controller error."
    );
}
