import { UserConfig } from "@hey-api/openapi-ts"

export default {
  input: "../../../services/headless-lms/server/openapi/auth.openapi.json",
  output: {
    clean: true,
    entryFile: false,
    fileName: {
      suffix: ".generated",
    },
    path: "src/generated/auth-api",
    header: () => {
      return [
        "// This file is auto-generated by running bin/generate-bindings or `pnpm run codegen:auth-api` in this package.",
        "// DO NOT EDIT THIS FILE MANUALLY",
        "/* eslint-disable */",
      ]
    },
  },
  plugins: [
    {
      name: "@hey-api/client-fetch",
      throwOnError: true,
    },
    "@hey-api/typescript",
    "zod",
    {
      name: "@hey-api/sdk",
      responseStyle: "data",
      validator: {
        response: "zod",
      },
    },
  ],
} satisfies UserConfig
