apiVersion: v1
kind: Service
metadata:
  name: example-exercise
  labels:
    app: example-exercise
spec:
  clusterIP: None
  ports:
    - port: 3002
      name: example-exercise
  selector:
    app: example-exercise
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-exercise
  labels:
    app: example-exercise
    deploymentType: without-init-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-exercise
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: example-exercise
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: example-exercise
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: example-exercise
      containers:
        - name: example-exercise
          image: example-exercise
          ports:
            - containerPort: 3002
              name: http
          env:
            - name: NEXT_PUBLIC_BASE_PATH
              value: "/example-exercise"
          resources:
            requests:
              memory: 100Mi
              cpu: 20m
            limits:
              memory: 300Mi
              cpu: 200m
