[package]
name = "headless-lms-credit-registration-workers"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
headless-lms-base = { path = "../../../foundation/base" }
headless-lms-use-cases = { path = "../../use-cases" }
headless-lms-external-service-clients = { path = "../../../infrastructure/external-service-clients" }
headless-lms-credit-registration = { path = "../../../features/credit-registration" }
anyhow = "1.0.104"
dotenvy = "0.15"
sqlx = { version = "0.9.0", default-features = false, features = [ "derive", "postgres" ] }
tracing = "0.1.44"
