resources:
  - ../base
  - postgres-dev.yml
  - headless-lms/env.yml
  - headless-lms/persistent-file-storage.yml
  - access-ingress-internally.yml
patches:
  # Remove cpu and memory resource without initContainer defined
  - path: patch-without-init-container.yml
    target:
      version: v1
      labelSelector: "deploymentType=without-init-container"
  # Remove cpu and memory resource with initContainer defined
  - path: patch-with-init-container.yml
    target:
      version: v1
      labelSelector: "deploymentType=with-init-container"
  - path: "headless-lms/patch-file-storage.yml"
    target:
      version: v1
      kind: Deployment
      name: "headless-lms"
