resources:
  - ../base
  - postgres-dev.yml
  - headless-lms/env.yml
  - headless-lms/persistent-file-storage.yml
patches:
  - path: headless-lms/patch-with-init-container.yml
    target:
      version: v1
      labelSelector: "deploymentType=with-init-container"
  - path: "headless-lms/patch-file-storage.yml"
    target:
      version: v1
      kind: Deployment
      name: "headless-lms"
