# these permissions allow the account to do a lot, so
# they are only added in the dev profile
- op: add
  path: "/rules"
  value:
    - apiGroups: [""]
      resources: ["pods", "pods/status", "pods/exec", "pods/delete"]
      verbs: ["create", "get", "exec", "delete"]
