name: Setup Node & pnpm
description: Install pnpm and let it handle Node version from pnpm-workspace.yaml
inputs:
  pnpm-version:
    description: "pnpm version to use"
    required: false
    default: "10.17.1"
runs:
  using: composite
  steps:
    - name: Cache pnpm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - shell: bash
      run: |
        # Install pnpm using corepack
        corepack enable
        corepack prepare pnpm@${{ inputs.pnpm-version }} --activate

        # pnpm will automatically install the Node version specified in pnpm-workspace.yaml
        # when running any pnpm command in the repo root
        cd $GITHUB_WORKSPACE
        pnpm --version

        echo "Node version: $(node -v)"
        echo "pnpm version: $(pnpm -v)"
