# The production environment is also used as a base for the test environment.
resources:
  - ../base
  - ./headless-lms/pdb.yml

patches:
  - path: patch-ingress.yml
    target:
      version: v1
      kind: Ingress
      name: project-331-ingress
  - path: patch-ingress-other-domains.yml
    target:
      version: v1
      kind: Ingress
      name: project-331-other-domains
  - path: ./headless-lms/patch-add-db-host-aliases.yml
    target:
      version: v1
      labelSelector: "needs-db=true"
  - path: ./headless-lms/patch-add-db-host-aliases-job.yml
    target:
      version: v1
      labelSelector: "needs-db=job"

# Patch image names
images:
  - name: course-material
    newName: eu.gcr.io/moocfi-public/secret-project-course-material-production-slim:latest
  - name: quizzes
    newName: eu.gcr.io/moocfi-public/secret-project-quizzes-production-slim:latest
  - name: tmc
    newName: eu.gcr.io/moocfi-public/secret-project-tmc-production-slim:latest
  - name: example-exercise
    newName: eu.gcr.io/moocfi-public/secret-project-example-exercise-production-slim:latest
  - name: main-frontend
    newName: eu.gcr.io/moocfi-public/secret-project-main-frontend-production-slim:latest
  - name: cms
    newName: eu.gcr.io/moocfi-public/secret-project-cms-production-slim:latest
  - name: headless-lms
    newName: eu.gcr.io/moocfi-public/secret-project-headless-lms-production-slim:latest

# Patch replicas
replicas:
  - name: course-material
    count: 2
  - name: quizzes
    count: 1
  - name: tmc
    count: 1
  - name: example-exercise
    count: 1
  - name: main-frontend
    count: 1
  - name: cms
    count: 1
  - name: headless-lms
    count: 4
