apiVersion: v1
kind: Service
metadata:
  name: quizzes
  labels:
    app: quizzes
spec:
  clusterIP: None
  ports:
    - port: 3004
      name: quizzes
  selector:
    app: quizzes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizzes
  labels:
    app: quizzes
    deploymentType: without-init-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quizzes
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: quizzes
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: quizzes
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: quizzes
      containers:
        - name: quizzes
          image: quizzes
          ports:
            - containerPort: 3004
              name: http
          env:
            - name: NEXT_PUBLIC_BASE_PATH
              value: "/quizzes"
          resources:
            requests:
              memory: 100Mi
              cpu: 20m
            limits:
              memory: 300Mi
              cpu: 200m
