apiVersion: v1
kind: Service
metadata:
  name: quizzes
  labels:
    app: quizzes
spec:
  clusterIP: None
  ports:
    - port: 3004
      name: quizzes
  selector:
    app: quizzes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizzes
  labels:
    app: quizzes
    deploymentType: without-init-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizzes
  template:
    metadata:
      labels:
        app: quizzes
    spec:
      containers:
        - name: quizzes
          image: quizzes
          ports:
            - containerPort: 3004
              name: http
          env:
            - name: NEXT_PUBLIC_BASE_PATH
              value: "/quizzes"
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
