/*!
The server that handles the requests.

## See also

* [headless_lms_utils]
* [headless_lms_models]
*/

pub mod config;
pub mod controllers;
pub mod domain;
pub mod openapi;
pub mod prelude;

#[cfg(test)]
mod env_guard;
pub mod programs;
#[cfg(test)]
pub mod test_helper;

#[macro_use]
extern crate tracing;

#[macro_use]
extern crate doc_macro;

use crate::config::FileStoreRuntimeConfig;
pub use headless_lms_base::tracing::setup_tracing;
use headless_lms_utils::file_store::{
    FileStore, google_cloud_file_store::GoogleCloudFileStore, local_file_store::LocalFileStore,
};
use oauth2::{EndpointNotSet, EndpointSet};
use std::sync::Arc;

pub type OAuthClient = oauth2::basic::BasicClient<
    EndpointSet,
    EndpointNotSet,
    EndpointNotSet,
    EndpointNotSet,
    EndpointSet,
>;

/**
Setups file store so that it can be passed to actix web as data.
Using Arc here so that this can be accessed from all the different worker threads.
*/
pub async fn setup_file_store(
    file_store_config: &FileStoreRuntimeConfig,
    base_url: &str,
) -> Arc<dyn FileStore + Send + Sync> {
    if file_store_config.use_google_cloud_storage {
        info!("Using Google Cloud Storage as the file store");
        let bucket_name = file_store_config
            .google_cloud_storage_bucket_name
            .clone()
            .expect("GOOGLE_CLOUD_STORAGE_BUCKET_NAME missing from runtime config");
        Arc::new(
            GoogleCloudFileStore::new(bucket_name)
                .await
                .expect("Failed to initialize file store"),
        )
    } else {
        info!("Using local file storage as the file store");
        Arc::new(
            LocalFileStore::new(
                "uploads".into(),
                format!("{base_url}/api/v0/files/uploads/"),
            )
            .expect("Failed to initialize file store"),
        )
    }
}

/// Includes the type's generated docs as a string.
/// generated by doc-file-generator as a string.
/// Used with the helper macro from the doc-macro crate: #[generated_doc]
#[macro_export]
macro_rules! generated_docs {
    ($t: expr_2021, ts) => {
        concat!(
            "## Response TypeScript definition\n",
            "```ts\n",
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/generated-docs/",
                stringify!($t),
                ".ts"
            )),
            "\n```\n",
        )
    };
    ($t: expr_2021, json) => {
        concat!(
            "## Example response\n",
            "```json\n",
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/generated-docs/",
                stringify!($t),
                ".json"
            )),
            "\n```\n",
        )
    };
    ($t: expr_2021) => {
        generated_docs!($t, json)
    };
}
