/*!
The server that handles the requests.

## See also

* [headless_lms_utils]
* [headless_lms_models]
*/

pub mod config;
pub mod controllers;
pub mod domain;
pub mod mock_suotar;
pub mod openapi;
pub mod prelude;
pub mod service_clients;

#[cfg(test)]
mod env_guard;
pub mod programs;
#[cfg(test)]
pub mod test_helper;

#[macro_use]
extern crate tracing;

#[macro_use]
extern crate doc_macro;

pub use headless_lms_base::tracing::setup_tracing;
use oauth2::{EndpointNotSet, EndpointSet};

pub type OAuthClient = oauth2::basic::BasicClient<
    EndpointSet,
    EndpointNotSet,
    EndpointNotSet,
    EndpointNotSet,
    EndpointSet,
>;

/// Includes the type's generated docs as a string.
/// generated by doc-file-generator as a string.
/// Used with the helper macro from the doc-macro crate: #[generated_doc]
#[macro_export]
macro_rules! generated_docs {
    ($t: expr_2021, ts) => {
        concat!(
            "## Response TypeScript definition\n",
            "```ts\n",
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/generated-docs/",
                stringify!($t),
                ".ts"
            )),
            "\n```\n",
        )
    };
    ($t: expr_2021, json) => {
        concat!(
            "## Example response\n",
            "```json\n",
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/generated-docs/",
                stringify!($t),
                ".json"
            )),
            "\n```\n",
        )
    };
    ($t: expr_2021) => {
        generated_docs!($t, json)
    };
}
