apiVersion: v1
kind: Service
metadata:
  name: playground
  labels:
    app: playground
spec:
  clusterIP: None
  ports:
    - port: 3005
      name: playground
  selector:
    app: playground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
  labels:
    app: playground
    deploymentType: without-init-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - name: playground
          image: playground
          ports:
            - containerPort: 3005
              name: http
          env:
            - name: BASE_PATH
              value: "/playground"
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
