apiVersion: v1
kind: Service
metadata:
  name: headless-lms
  labels:
    app: headless-lms
spec:
  clusterIP: None
  ports:
    - port: 3001
      name: headless-lms
  selector:
    app: headless-lms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-lms
  labels:
    app: headless-lms
    deploymentType: with-init-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headless-lms
  template:
    metadata:
      labels:
        app: headless-lms
    spec:
      containers:
        - name: headless-lms
          image: headless-lms
          ports:
            - containerPort: 3001
              name: headless-lms
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
      initContainers:
        - name: headless-lms-wait-for-db
          image: headless-lms
          command:
            - bash
            - "-c"
            - |
              echo Waiting for postgres to be available
              wait-for-it --timeout=120 postgres:5432
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
---
# Migrations
apiVersion: batch/v1
kind: Job
metadata:
  name: headless-lms-run-migrations
  labels:
    deploymentType: without-init-container
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        waitToBeReady: "false"
    spec:
      containers:
        - name: headless-lms-run-migrations
          image: headless-lms
          command:
            - bash
            - "-c"
            - |
              echo Waiting for postgres to be available
              wait-for-it --timeout=120 postgres:5432
              echo Running migrations
              cargo sqlx migrate run
              echo Migrations complete
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
          envFrom:
            - configMapRef:
                name: postgres-configuration
      restartPolicy: Never
