apiVersion: apps/v1
kind: Deployment
metadata:
  name: regrader
  labels:
    app: regrader
    deploymentType: with-init-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regrader
  template:
    metadata:
      labels:
        app: regrader
    spec:
      containers:
        - name: regrader
          image: headless-lms
          command: ["cargo", "run", "--bin", "regrader"]
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
      initContainers:
        - name: headless-lms-wait-for-db
          image: headless-lms
          command:
            - bash
            - "-c"
            - |
              echo Waiting for postgres to be available
              timeout 120 ./wait-for-db.sh
              ./wait-for-db-migrations.sh
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
