export default {
  input: "../headless-lms/server/openapi/cms.openapi.json",
  output: {
    clean: true,
    fileName: {
      suffix: ".generated",
    },
    path: "../cms/src/generated/api",
    header: () => {
      return [
        "// This file is auto-generated.",
        "// DO NOT EDIT THIS FILE MANUALLY",
        "/* eslint-disable */",
      ]
    },
  },
  plugins: ["@hey-api/typescript", "zod"],
}
