import { UserConfig } from "@hey-api/openapi-ts"

const createConfig = (input: string, path: string) =>
  ({
    input,
    output: {
      clean: true,
      entryFile: false,
      fileName: {
        suffix: ".generated",
      },
      path,
      header: () => {
        return [
          "// This file is auto-generated by running bin/generate-bindings",
          "// DO NOT EDIT THIS FILE MANUALLY",
          "/* eslint-disable */",
        ]
      },
    },
    plugins: [
      {
        name: "@hey-api/client-fetch",
        throwOnError: true,
      },
      "@hey-api/typescript",
      "zod",
      {
        name: "@hey-api/sdk",
        responseStyle: "data",
        validator: {
          response: "zod",
        },
      },
      "@tanstack/react-query",
    ],
  }) satisfies UserConfig

export default createConfig(
  "../headless-lms/server/openapi/cms.openapi.json",
  "../cms/src/generated/api",
)
