/* eslint-disable @typescript-eslint/no-empty-interface */

// ###########################################
// ## This file is autogenerated by running ##
// ## 'bin/extract-gutenberg-types'         ##
// ## in the root of the repo.              ##
// ##                                       ##
// ## Do not edit this file by hand.        ##
// ###########################################

import type { StringWithHTML } from "."

/**
 * @deprecated
 */
export interface AudioDeprecated1Attributes {
  src?: string
  caption?: string
  id?: number
  autoplay?: boolean
  loop?: boolean
  preload?: string
}

/**
 * @deprecated
 */
export interface BlockDeprecated1Attributes {
  ref?: number
  content?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated
 */
export interface BlockDeprecated2Attributes {
  ref?: number
  overrides?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated
 */
export interface ButtonDeprecated10Attributes {
  url?: string
  title?: string
  text?: string
  color?: string
  textColor?: string
  align: string
}

/**
 * @deprecated
 */
export interface ButtonDeprecated11Attributes {
  url?: string
  title?: string
  text?: string
  color?: string
  textColor?: string
  align: string
}

/**
 * @deprecated
 */
export interface ButtonDeprecated1Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  width?: number
}

/**
 * @deprecated
 */
export interface ButtonDeprecated2Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  width?: number
}

/**
 * @deprecated
 */
export interface ButtonDeprecated3Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  width?: number
}

/**
 * @deprecated
 */
export interface ButtonDeprecated4Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  borderRadius?: number
  backgroundColor?: string
  textColor?: string
  gradient?: string
  style?: {
    [k: string]: unknown
  }
  width?: number
}

/**
 * @deprecated
 */
export interface ButtonDeprecated5Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  borderRadius?: number
  backgroundColor?: string
  textColor?: string
  gradient?: string
  style?: {
    [k: string]: unknown
  }
  width?: number
}

/**
 * @deprecated
 */
export interface ButtonDeprecated6Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  borderRadius?: number
  backgroundColor?: string
  textColor?: string
  gradient?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated
 */
export interface ButtonDeprecated7Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  borderRadius?: number
  backgroundColor?: string
  textColor?: string
  customBackgroundColor?: string
  customTextColor?: string
  customGradient?: string
  gradient?: string
}

/**
 * @deprecated
 */
export interface ButtonDeprecated8Attributes {
  url?: string
  title?: string
  text?: string
  align: string
  backgroundColor?: string
  textColor?: string
  customBackgroundColor?: string
  customTextColor?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
}

/**
 * @deprecated
 */
export interface ButtonDeprecated9Attributes {
  url?: string
  title?: string
  text?: string
  align: string
  backgroundColor?: string
  textColor?: string
  customBackgroundColor?: string
  customTextColor?: string
}

/**
 * @deprecated
 */
export interface ButtonsDeprecated1Attributes {
  contentJustification?: string
  orientation: string
}

/**
 * @deprecated
 */
export interface ButtonsDeprecated2Attributes {}

/**
 * @deprecated
 */
export interface ColumnDeprecated1Attributes {
  verticalAlignment?: string
  width?: number
}

/**
 * @deprecated
 */
export interface ColumnsDeprecated1Attributes {
  verticalAlignment?: string
  backgroundColor?: string
  customBackgroundColor?: string
  customTextColor?: string
  textColor?: string
}

/**
 * @deprecated
 */
export interface ColumnsDeprecated2Attributes {
  columns: number
}

/**
 * @deprecated
 */
export interface ColumnsDeprecated3Attributes {
  columns: number
}

/**
 * @deprecated
 */
export interface EmbedDeprecated1Attributes {
  url?: string
  caption?: StringWithHTML
  type?: string
  providerNameSlug?: string
  allowResponsive: boolean
  responsive: boolean
  previewable: boolean
}

/**
 * @deprecated
 */
export interface EmbedDeprecated2Attributes {
  url?: string
  caption?: StringWithHTML
  type?: string
  providerNameSlug?: string
  allowResponsive: boolean
  responsive: boolean
  previewable: boolean
}

/**
 * @deprecated
 */
export interface FileDeprecated1Attributes {
  id?: number
  href?: string
  fileId?: string
  fileName?: string
  textLinkHref?: string
  textLinkTarget?: string
  showDownloadButton: boolean
  downloadButtonText?: string
  displayPreview?: boolean
  previewHeight: number
}

/**
 * @deprecated
 */
export interface FileDeprecated2Attributes {
  id?: number
  href?: string
  fileId?: string
  fileName?: string
  textLinkHref?: string
  textLinkTarget?: string
  showDownloadButton: boolean
  downloadButtonText?: string
  displayPreview?: boolean
  previewHeight: number
}

/**
 * @deprecated
 */
export interface FileDeprecated3Attributes {
  id?: number
  href?: string
  fileName?: string
  textLinkHref?: string
  textLinkTarget?: string
  showDownloadButton: boolean
  downloadButtonText?: string
  displayPreview?: boolean
  previewHeight: number
}

/**
 * @deprecated
 */
export interface HeadingDeprecated1Attributes {
  textAlign?: string
  content: string
  level: number
  placeholder?: string
}

/**
 * @deprecated
 */
export interface HeadingDeprecated2Attributes {
  align?: string
  content: string
  level: number
  placeholder?: string
}

/**
 * @deprecated
 */
export interface HeadingDeprecated3Attributes {
  align?: string
  content: string
  level: number
  placeholder?: string
  customTextColor?: string
  textColor?: string
}

/**
 * @deprecated
 */
export interface HeadingDeprecated4Attributes {
  align?: string
  content: string
  level: number
  placeholder?: string
  customTextColor?: string
  textColor?: string
}

/**
 * @deprecated
 */
export interface HeadingDeprecated5Attributes {
  align?: string
  content: string
  level: number
  placeholder?: string
  customTextColor?: string
  textColor?: string
}

/**
 * @deprecated
 */
export interface ImageDeprecated1Attributes {
  align?: string
  behaviors?: {
    [k: string]: unknown
  }
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: string
  height?: string
  aspectRatio?: string
  scale?: string
  sizeSlug?: string
  linkDestination?: string
  linkTarget?: string
}

/**
 * @deprecated
 */
export interface ImageDeprecated2Attributes {
  align?: string
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: number
  height?: number
  aspectRatio?: string
  scale?: string
  sizeSlug?: string
  linkDestination?: string
  linkTarget?: string
}

/**
 * @deprecated
 */
export interface ImageDeprecated3Attributes {
  align?: string
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: number
  height?: number
  aspectRatio?: string
  scale?: string
  sizeSlug?: string
  linkDestination?: string
  linkTarget?: string
}

/**
 * @deprecated
 */
export interface ImageDeprecated4Attributes {
  align?: string
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: number
  height?: number
  sizeSlug?: string
  linkDestination?: string
  linkTarget?: string
}

/**
 * @deprecated
 */
export interface ImageDeprecated5Attributes {
  align?: string
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: number
  height?: number
  sizeSlug?: string
  linkDestination?: string
  linkTarget?: string
}

/**
 * @deprecated
 */
export interface ImageDeprecated6Attributes {
  url?: string
  alt: string
  caption?: unknown[]
  href?: string
  id?: number
  align?: string
  width?: number
  height?: number
  linkDestination: string
}

/**
 * @deprecated
 */
export interface ImageDeprecated7Attributes {
  url?: string
  alt: string
  caption?: unknown[]
  href?: string
  id?: number
  align?: string
  width?: number
  height?: number
}

/**
 * @deprecated
 */
export interface ImageDeprecated8Attributes {
  url?: string
  alt: string
  caption?: unknown[]
  href?: string
  id?: number
  align?: string
  width?: number
  height?: number
}

/**
 * @deprecated
 */
export interface ListDeprecated1Attributes {
  ordered: boolean
  values: string
  type?: string
  start?: number
  reversed?: boolean
  placeholder?: string
}

/**
 * @deprecated
 */
export interface ListDeprecated2Attributes {
  ordered: boolean
  values: string
  type?: string
  start?: number
  reversed?: boolean
  placeholder?: string
}

/**
 * @deprecated
 */
export interface ListDeprecated3Attributes {
  ordered: boolean
  values: string
  type?: string
  start?: number
  reversed?: boolean
  placeholder?: string
}

/**
 * @deprecated
 */
export interface ListDeprecated4Attributes {
  ordered: boolean
  values: string
  type?: string
  start?: number
  reversed?: boolean
  placeholder?: string
}

/**
 * @deprecated
 */
export interface ParagraphDeprecated1Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: string
  direction?: "ltr" | "rtl"
  customTextColor?: string
  customBackgroundColor?: string
  customFontSize?: number
}

/**
 * @deprecated
 */
export interface ParagraphDeprecated2Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: string
  direction?: "ltr" | "rtl"
  customTextColor?: string
  customBackgroundColor?: string
  customFontSize?: number
}

/**
 * @deprecated
 */
export interface ParagraphDeprecated3Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: string
  direction?: "ltr" | "rtl"
  customTextColor?: string
  customBackgroundColor?: string
  customFontSize?: number
}

/**
 * @deprecated
 */
export interface ParagraphDeprecated4Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: string
  direction?: "ltr" | "rtl"
  customTextColor?: string
  customBackgroundColor?: string
  customFontSize?: number
  width?: string
}

/**
 * @deprecated
 */
export interface ParagraphDeprecated5Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: number
  direction?: "ltr" | "rtl"
}

/**
 * @deprecated
 */
export interface ParagraphDeprecated6Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: string
  direction?: "ltr" | "rtl"
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated
 */
export interface PullquoteDeprecated1Attributes {
  value?: string
  citation: string
  textAlign?: string
}

/**
 * @deprecated
 */
export interface PullquoteDeprecated2Attributes {
  value?: string
  citation: string
  mainColor?: string
  customMainColor?: string
  textColor?: string
  customTextColor?: string
}

/**
 * @deprecated
 */
export interface PullquoteDeprecated3Attributes {
  value?: string
  citation: string
  mainColor?: string
  customMainColor?: string
  textColor?: string
  customTextColor?: string
  figureStyle?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated
 */
export interface PullquoteDeprecated4Attributes {
  value?: string
  citation: string
  mainColor?: string
  customMainColor?: string
  textColor?: string
  customTextColor?: string
}

/**
 * @deprecated
 */
export interface PullquoteDeprecated5Attributes {
  value?: string
  citation: string
  mainColor?: string
  customMainColor?: string
  textColor?: string
  customTextColor?: string
}

/**
 * @deprecated
 */
export interface PullquoteDeprecated6Attributes {
  value?: string
  citation?: string
  mainColor?: string
  customMainColor?: string
  textColor?: string
  customTextColor?: string
  align: string
}

/**
 * @deprecated
 */
export interface QuoteDeprecated1Attributes {
  value: string
  citation: string
  align?: string
}

/**
 * @deprecated
 */
export interface QuoteDeprecated2Attributes {
  value: string
  citation: string
  align?: string
}

/**
 * @deprecated
 */
export interface QuoteDeprecated3Attributes {
  value: string
  citation: string
  align?: string
}

/**
 * @deprecated
 */
export interface QuoteDeprecated4Attributes {
  value: string
  citation: string
  align?: string
  style: number
}

/**
 * @deprecated
 */
export interface QuoteDeprecated5Attributes {
  value: string
  citation: string
  align?: string
  style: number
}

/**
 * @deprecated
 */
export interface SeparatorDeprecated1Attributes {
  color?: string
  customColor?: string
}

/**
 * @deprecated
 */
export interface SpacerDeprecated1Attributes {
  height: number
  width?: number
}

/**
 * @deprecated
 */
export interface VerseDeprecated1Attributes {
  content: string
  textAlign?: string
}

/**
 * @deprecated
 */
export interface VerseDeprecated2Attributes {
  content: string
  textAlign?: string
}
