/* eslint-disable @typescript-eslint/no-empty-interface */

// ###########################################
// ## This file is autogenerated by running ##
// ## 'bin/extract-gutenberg-types'         ##
// ## in the root of the repo.              ##
// ##                                       ##
// ## Do not edit this file by hand.        ##
// ###########################################

export interface ParagraphAttributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  direction?: "ltr" | "rtl"
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of ParagraphAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ParagraphDeprecated1Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: string
  direction?: "ltr" | "rtl"
  customTextColor?: string
  customBackgroundColor?: string
  customFontSize?: number
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ParagraphAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ParagraphDeprecated2Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: string
  direction?: "ltr" | "rtl"
  customTextColor?: string
  customBackgroundColor?: string
  customFontSize?: number
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ParagraphAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ParagraphDeprecated3Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: string
  direction?: "ltr" | "rtl"
  customTextColor?: string
  customBackgroundColor?: string
  customFontSize?: number
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ParagraphAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ParagraphDeprecated4Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: string
  direction?: "ltr" | "rtl"
  customTextColor?: string
  customBackgroundColor?: string
  customFontSize?: number
  width?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ParagraphAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ParagraphDeprecated5Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: number
  direction?: "ltr" | "rtl"
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ParagraphAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ParagraphDeprecated6Attributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  textColor?: string
  backgroundColor?: string
  fontSize?: string
  direction?: "ltr" | "rtl"
  style?: {
    [k: string]: unknown
  }
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

export interface ImageAttributes {
  align?: string
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: number
  height?: number
  sizeSlug?: string
  linkDestination: string
  linkTarget?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  style?: {
    [k: string]: unknown
  }
  blurDataUrl: string
}

/**
 * @deprecated This is an older version of ImageAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ImageDeprecated1Attributes {
  align?: string
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: number
  height?: number
  sizeSlug?: string
  linkDestination: string
  linkTarget?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  style?: {
    [k: string]: unknown
  }
  blurDataUrl: string
}

/**
 * @deprecated This is an older version of ImageAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ImageDeprecated2Attributes {
  align?: string
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: number
  height?: number
  sizeSlug?: string
  linkDestination: string
  linkTarget?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  style?: {
    [k: string]: unknown
  }
  blurDataUrl: string
}

/**
 * @deprecated This is an older version of ImageAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ImageDeprecated3Attributes {
  align?: string
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: number
  height?: number
  sizeSlug?: string
  linkDestination: string
  linkTarget?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
  blurDataUrl: string
}

/**
 * @deprecated This is an older version of ImageAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ImageDeprecated4Attributes {
  align?: string
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: number
  height?: number
  sizeSlug?: string
  linkDestination: string
  linkTarget?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
  blurDataUrl: string
}

/**
 * @deprecated This is an older version of ImageAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ImageDeprecated5Attributes {
  align?: string
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: number
  height?: number
  sizeSlug?: string
  linkDestination: string
  linkTarget?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
  blurDataUrl: string
}

export interface HeadingAttributes {
  textAlign?: string
  content: string
  level: number
  placeholder?: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of HeadingAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface HeadingDeprecated1Attributes {
  textAlign?: string
  content: string
  level: number
  placeholder?: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of HeadingAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface HeadingDeprecated2Attributes {
  align?: string
  content: string
  level: number
  placeholder?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of HeadingAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface HeadingDeprecated3Attributes {
  align?: string
  content: string
  level: number
  placeholder?: string
  customTextColor?: string
  textColor?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
}

/**
 * @deprecated This is an older version of HeadingAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface HeadingDeprecated4Attributes {
  align?: string
  content: string
  level: number
  placeholder?: string
  customTextColor?: string
  textColor?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
}

/**
 * @deprecated This is an older version of HeadingAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface HeadingDeprecated5Attributes {
  align?: string
  content: string
  level: number
  placeholder?: string
  customTextColor?: string
  textColor?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
}

export interface ListAttributes {
  ordered: boolean
  values: string
  type?: string
  start?: number
  reversed?: boolean
  placeholder?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of ListAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ListDeprecated1Attributes {
  ordered: boolean
  values: string
  type?: string
  start?: number
  reversed?: boolean
  placeholder?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of ListAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ListDeprecated2Attributes {
  ordered: boolean
  values: string
  type?: string
  start?: number
  reversed?: boolean
  placeholder?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface ListItemAttributes {
  placeholder?: string
  content: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface QuoteAttributes {
  value: string
  citation: string
  align?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of QuoteAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface QuoteDeprecated1Attributes {
  value: string
  citation: string
  align?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of QuoteAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface QuoteDeprecated2Attributes {
  value: string
  citation: string
  align?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of QuoteAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface QuoteDeprecated3Attributes {
  value: string
  citation: string
  align?: string
  style: number
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of QuoteAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface QuoteDeprecated4Attributes {
  value: string
  citation: string
  align?: string
  style: number
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

export interface AudioAttributes {
  src?: string
  caption?: string
  id?: number
  autoplay?: boolean
  loop?: boolean
  preload?: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of AudioAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface AudioDeprecated1Attributes {
  src?: string
  caption?: string
  id?: number
  autoplay?: boolean
  loop?: boolean
  preload?: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

export interface ButtonAttributes {
  textAlign?: string
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  width?: number
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of ButtonAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonDeprecated1Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  width?: number
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of ButtonAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonDeprecated2Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  width?: number
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of ButtonAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonDeprecated3Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  width?: number
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of ButtonAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonDeprecated4Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  borderRadius?: number
  backgroundColor?: string
  textColor?: string
  gradient?: string
  style?: {
    [k: string]: unknown
  }
  width?: number
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
}

/**
 * @deprecated This is an older version of ButtonAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonDeprecated5Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  borderRadius?: number
  backgroundColor?: string
  textColor?: string
  gradient?: string
  style?: {
    [k: string]: unknown
  }
  width?: number
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
}

/**
 * @deprecated This is an older version of ButtonAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonDeprecated6Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  borderRadius?: number
  backgroundColor?: string
  textColor?: string
  gradient?: string
  style?: {
    [k: string]: unknown
  }
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ButtonAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonDeprecated7Attributes {
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  borderRadius?: number
  backgroundColor?: string
  textColor?: string
  customBackgroundColor?: string
  customTextColor?: string
  customGradient?: string
  gradient?: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ButtonAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonDeprecated8Attributes {
  url?: string
  title?: string
  text?: string
  align: string
  backgroundColor?: string
  textColor?: string
  customBackgroundColor?: string
  customTextColor?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ButtonAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonDeprecated9Attributes {
  url?: string
  title?: string
  text?: string
  align: string
  backgroundColor?: string
  textColor?: string
  customBackgroundColor?: string
  customTextColor?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ButtonAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonDeprecated10Attributes {
  url?: string
  title?: string
  text?: string
  color?: string
  textColor?: string
  align: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ButtonAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonDeprecated11Attributes {
  url?: string
  title?: string
  text?: string
  color?: string
  textColor?: string
  align: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

export interface ButtonsAttributes {
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
  layout?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of ButtonsAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonsDeprecated1Attributes {
  contentJustification?: string
  orientation: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of ButtonsAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ButtonsDeprecated2Attributes {
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
}

export interface CodeAttributes {
  content?: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface ColumnAttributes {
  verticalAlignment?: string
  width?: string
  allowedBlocks?: unknown[]
  templateLock?: "all" | "insert" | "contentOnly" | false
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
  layout?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of ColumnAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ColumnDeprecated1Attributes {
  verticalAlignment?: string
  width?: number
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

export interface ColumnsAttributes {
  verticalAlignment?: string
  isStackedOnMobile: boolean
  templateLock?: "all" | "insert" | "contentOnly" | false
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
  layout?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of ColumnsAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ColumnsDeprecated1Attributes {
  verticalAlignment?: string
  backgroundColor?: string
  customBackgroundColor?: string
  customTextColor?: string
  textColor?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ColumnsAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ColumnsDeprecated2Attributes {
  columns: number
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of ColumnsAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface ColumnsDeprecated3Attributes {
  columns: number
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

export interface EmbedAttributes {
  url?: string
  caption?: string
  type?: string
  providerNameSlug?: string
  allowResponsive: boolean
  responsive: boolean
  previewable: boolean
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  className?: string
  style?: {
    [k: string]: unknown
  }
  height?: number
  title?: string
}

/**
 * @deprecated This is an older version of EmbedAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface EmbedDeprecated1Attributes {
  url?: string
  caption?: string
  type?: string
  providerNameSlug?: string
  allowResponsive: boolean
  responsive: boolean
  previewable: boolean
  lock?: {
    [k: string]: unknown
  }
  className?: string
  height?: number
  title?: string
}

/**
 * @deprecated This is an older version of EmbedAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface EmbedDeprecated2Attributes {
  url?: string
  caption?: string
  type?: string
  providerNameSlug?: string
  allowResponsive: boolean
  responsive: boolean
  previewable: boolean
  lock?: {
    [k: string]: unknown
  }
  className?: string
  height?: number
  title?: string
}

export interface FileAttributes {
  id?: number
  href?: string
  fileId?: string
  fileName?: string
  textLinkHref?: string
  textLinkTarget?: string
  showDownloadButton: boolean
  downloadButtonText?: string
  displayPreview?: boolean
  previewHeight: number
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of FileAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface FileDeprecated1Attributes {
  id?: number
  href?: string
  fileId?: string
  fileName?: string
  textLinkHref?: string
  textLinkTarget?: string
  showDownloadButton: boolean
  downloadButtonText?: string
  displayPreview?: boolean
  previewHeight: number
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
}

/**
 * @deprecated This is an older version of FileAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface FileDeprecated2Attributes {
  id?: number
  href?: string
  fileId?: string
  fileName?: string
  textLinkHref?: string
  textLinkTarget?: string
  showDownloadButton: boolean
  downloadButtonText?: string
  displayPreview?: boolean
  previewHeight: number
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
}

/**
 * @deprecated This is an older version of FileAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface FileDeprecated3Attributes {
  id?: number
  href?: string
  fileName?: string
  textLinkHref?: string
  textLinkTarget?: string
  showDownloadButton: boolean
  downloadButtonText?: string
  displayPreview?: boolean
  previewHeight: number
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
}

export interface HtmlAttributes {
  content?: string
  lock?: {
    [k: string]: unknown
  }
}

export interface PreformattedAttributes {
  content: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface PullquoteAttributes {
  value?: string
  citation: string
  textAlign?: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of PullquoteAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface PullquoteDeprecated1Attributes {
  value?: string
  citation: string
  textAlign?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of PullquoteAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface PullquoteDeprecated2Attributes {
  value?: string
  citation: string
  mainColor?: string
  customMainColor?: string
  textColor?: string
  customTextColor?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of PullquoteAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface PullquoteDeprecated3Attributes {
  value?: string
  citation: string
  mainColor?: string
  customMainColor?: string
  textColor?: string
  customTextColor?: string
  figureStyle?: {
    [k: string]: unknown
  }
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of PullquoteAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface PullquoteDeprecated4Attributes {
  value?: string
  citation: string
  mainColor?: string
  customMainColor?: string
  textColor?: string
  customTextColor?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of PullquoteAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface PullquoteDeprecated5Attributes {
  value?: string
  citation: string
  mainColor?: string
  customMainColor?: string
  textColor?: string
  customTextColor?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

/**
 * @deprecated This is an older version of PullquoteAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface PullquoteDeprecated6Attributes {
  value?: string
  citation?: string
  mainColor?: string
  customMainColor?: string
  textColor?: string
  customTextColor?: string
  align: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

export interface BlockAttributes {
  ref?: number
  lock?: {
    [k: string]: unknown
  }
}

export interface SeparatorAttributes {
  opacity: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of SeparatorAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface SeparatorDeprecated1Attributes {
  color?: string
  customColor?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

export interface SpacerAttributes {
  height: string
  width?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of SpacerAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface SpacerDeprecated1Attributes {
  height: number
  width?: number
  lock?: {
    [k: string]: unknown
  }
  className?: string
}

export interface TableAttributes {
  hasFixedLayout: boolean
  caption: string
  head: Cells[]
  body: Cells[]
  foot: Cells[]
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}
export interface Cells {
  cells?: CellAttributes[]
}
export interface CellAttributes {
  content?: string
  tag?: string
  scope?: string
  align?: string
  colspan?: string
  rowspan?: string
}

export interface VerseAttributes {
  content: string
  textAlign?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of VerseAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface VerseDeprecated1Attributes {
  content: string
  textAlign?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

/**
 * @deprecated This is an older version of VerseAttributes. We may need to support rendering this if someone has created content using an older version of Gutenberg.
 */

export interface VerseDeprecated2Attributes {
  content: string
  textAlign?: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
}
