/* eslint-disable @typescript-eslint/no-empty-interface */

// ###########################################
// ## This file is autogenerated by running ##
// ## 'bin/extract-gutenberg-types'         ##
// ## in the root of the repo.              ##
// ##                                       ##
// ## Do not edit this file by hand.        ##
// ###########################################

export interface AudioAttributes {
  src?: string
  caption?: string
  id?: number
  autoplay?: boolean
  loop?: boolean
  preload?: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  style?: {
    [k: string]: unknown
  }
}

export interface BlockAttributes {
  ref?: number
  lock?: {
    [k: string]: unknown
  }
}

export interface ButtonAttributes {
  textAlign?: string
  url?: string
  title?: string
  text?: string
  linkTarget?: string
  rel?: string
  placeholder?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  width?: number
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface ButtonsAttributes {
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
  layout?: {
    [k: string]: unknown
  }
}

export interface CodeAttributes {
  content?: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface ColumnAttributes {
  verticalAlignment?: string
  width?: string
  allowedBlocks?: unknown[]
  templateLock?: "all" | "insert" | "contentOnly" | false
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
  layout?: {
    [k: string]: unknown
  }
}

export interface ColumnsAttributes {
  verticalAlignment?: string
  isStackedOnMobile: boolean
  templateLock?: "all" | "insert" | "contentOnly" | false
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
  layout?: {
    [k: string]: unknown
  }
}

export interface EmbedAttributes {
  url?: string
  caption?: string
  type?: string
  providerNameSlug?: string
  allowResponsive: boolean
  responsive: boolean
  previewable: boolean
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  className?: string
  style?: {
    [k: string]: unknown
  }
  height?: number
  title?: string
}

export interface FileAttributes {
  id?: number
  href?: string
  fileId?: string
  fileName?: string
  textLinkHref?: string
  textLinkTarget?: string
  showDownloadButton: boolean
  downloadButtonText?: string
  displayPreview?: boolean
  previewHeight: number
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  style?: {
    [k: string]: unknown
  }
}

export interface HeadingAttributes {
  textAlign?: string
  content: string
  level: number
  placeholder?: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface HtmlAttributes {
  content?: string
  lock?: {
    [k: string]: unknown
  }
}

export interface ImageAttributes {
  align?: string
  url?: string
  alt: string
  caption?: string
  title?: string
  href?: string
  rel?: string
  linkClass?: string
  id?: number
  width?: string
  height?: string
  aspectRatio?: string
  scale?: string
  sizeSlug?: string
  linkDestination: string
  linkTarget?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  style?: {
    [k: string]: unknown
  }
  blurDataUrl: string
}

export interface ListAttributes {
  ordered: boolean
  values: string
  type?: string
  start?: number
  reversed?: boolean
  placeholder?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface ListItemAttributes {
  placeholder?: string
  content: string
  lock?: {
    [k: string]: unknown
  }
  className?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface ParagraphAttributes {
  align?: string
  content: string
  dropCap: boolean
  placeholder?: string
  direction?: "ltr" | "rtl"
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface PreformattedAttributes {
  content: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface PullquoteAttributes {
  value?: string
  citation: string
  textAlign?: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface QuoteAttributes {
  value: string
  citation: string
  align?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}

export interface SeparatorAttributes {
  opacity: string
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  style?: {
    [k: string]: unknown
  }
}

export interface SpacerAttributes {
  height: string
  width?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  style?: {
    [k: string]: unknown
  }
}

export interface TableAttributes {
  hasFixedLayout: boolean
  caption: string
  head: Cells[]
  body: Cells[]
  foot: Cells[]
  align?: "left" | "center" | "right" | "wide" | "full" | ""
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}
export interface Cells {
  cells?: CellAttributes[]
}
export interface CellAttributes {
  content?: string
  tag?: string
  scope?: string
  align?: string
  colspan?: string
  rowspan?: string
}

export interface VerseAttributes {
  content: string
  textAlign?: string
  lock?: {
    [k: string]: unknown
  }
  anchor?: string
  className?: string
  borderColor?: string
  backgroundColor?: string
  textColor?: string
  gradient?: string
  fontFamily?: string
  fontSize?: string
  style?: {
    [k: string]: unknown
  }
}
