engineStrict: true

linkWorkspacePackages: true

pmOnFail: download

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false

nodeVersion: 24.18.0

overrides:
  picomatch@>=4.0.0 <4.0.4: ">=4.0.4"

preferFrozenLockfile: true

preferWorkspacePackages: true

registrySupportsTimeField: false

resolutionMode: time-based

saveWorkspaceProtocol: rolling

sharedWorkspaceLockfile: false

strictDepBuilds: true

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  node: false

trustLockfile: true

confirmModulesPurge: false

updateNotifier: false

verifyDepsBeforeRun: install
