[package]
name = "headless-lms-file-store"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
headless-lms-utils = { path = "../../../foundation/utils" }
headless-lms-base = { path = "../../../foundation/base" }
anyhow = "1.0.104"
async-trait = "0.1.92"
blake3 = "1.8.7"
bytes = "1.12.1"
futures = "0.3.34"
rand = "0.10.2"
tempfile = "3.27.0"
tokio = { workspace = true, features = [ "macros", "time" ] }
tokio-util = { version = "0.7.19", features = [ "io" ] }
tracing = "0.1.44"
uuid = { version = "1.26.0", features = [ "serde" ] }
