#!/bin/sh

command -v git-lfs >/dev/null 2>&1 && git lfs post-commit "$@" || true

echo ""
echo "👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇"
echo ""
printf "\033[1;31m⚠️  ONCE YOU'RE READY WITH THE BRANCH, RUN bin/git-run-branch-ready-checks AND MAKE SURE EVERYTHING PASSES ⚠️\033[0m\n"
echo ""
echo "👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆"
echo ""

