name: Code Style
on:
  push:
    branches:
      - master
      - canary
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile
      - name: Run actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
      - name: Eslint
        run: npm run eslint:ci
      - name: Stylelint
        run: npm run lint:css
      - name: Cargo fmt
        run: cargo fmt --manifest-path services/headless-lms/Cargo.toml --all -- --files-with-diff --check
