name: Code Style
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm ci
      - name: Eslint
        run: npm run eslint:ci
      - name: Stylelint
        run: npm run lint:css
      - name: Cargo fmt
        run: cargo fmt --manifest-path services/headless-lms/Cargo.toml --all -- --files-with-diff --check
