name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cargo clippy
        run: cargo clippy --manifest-path services/headless-lms/Cargo.toml -- -D warnings
      - name: Build
        run: cargo build --verbose
        working-directory: ./services/headless-lms
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./services/headless-lms
