name: "Pull Request Labeler"

permissions: read-all

on:
  - pull_request_target

jobs:
  label_pull_requests:
    if: ${{ github.event.pull_request.head.repo.fork == false || github.actor == 'dependabot[bot]' }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
