name: System tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install kustomize, kubectl and skaffold
        uses: daisaru11/setup-cd-tools@v1
        with:
          kubectl: "1.19.2"
          kustomize: "4.1.3"
          skaffold: "1.24.0"
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        run: bin/minikube-start

      - name: Build
        run: bin/test
        working-directory: ./

      - name: Run system tests
        uses: microsoft/playwright-github-action@v1
        run: npm run test
        working-directory: ./system-tests/
