name: System tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  system-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install kustomize, kubectl and skaffold
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kubectl: "1.19.2"
          kustomize: "4.1.3"
          skaffold: "1.24.0"

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Run npm ci for shared-modules
        run: npm ci
        working-directory: ./

      - name: Build and run environment
        run: bin/test
        working-directory: ./

      - uses: microsoft/playwright-github-action@v1
      - name: Run system tests
        run: npm run test
        working-directory: ./system-tests/
