name: System tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  system-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install kustomize, kubectl and skaffold
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kubectl: "1.19.2"
          kustomize: "4.1.3"
          skaffold: "1.24.0"

      - name: Authenticate to Google Cloud
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          echo Authenticating to Google Cloud
          echo $GCLOUD_SERVICE_KEY | python -m base64 -d > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          if gcloud auth configure-docker -q; then
              echo "Authenticated to Google Cloud..."
          else
              echo "Authentication to Google Cloud failed. Exiting..."
              exit 1
          fi

      - name: Start minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: "v1.20.0"
          kubernetes version: "v1.21.0"
          start args: "--addons ingress"

      - name: Run npm ci for shared-modules
        run: npm ci

      - name: Build and deploy
        run: |
          skaffold build -p test
          skaffold run --port-forward --force -p test --tail &
          sleep 10
          kubectl get pods -o name --selector='waitToBeReady!=false' | xargs kubectl wait --timeout=600s --for=condition=ready
          echo "All pods ready"

      - name: Setup test db
        run: bin/setup-system-test-db

      - name: Configure ingress
        run: echo "$(minikube ip) project-331.local" >> sudo tee /etc/hosts

      - name: Setup system test environment
        run: npm ci
        working-directory: ./system-tests/

      - name: Run system tests
        run: npm run test
        working-directory: ./system-tests/

      - name: Push push-images
        run: skaffold build -p test,push-images
        if: ${{ github.ref == 'refs/heads/master' }}
