name: System tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  system-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install kustomize, kubectl and skaffold
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kubectl: "1.19.2"
          kustomize: "4.1.3"
          skaffold: "1.24.0"

      - name: Restore cluster from cache
        id: restore-minikube-cache
        uses: actions/cache@v2
        env:
          cache-name: minikube-cache
        with:
          path: ~/.minikube/
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Start minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: "v1.20.0"
          kubernetes version: "v1.21.0"
          start args: "--addons ingress"
      - name: Configure ingress
        run: echo "$(minikube ip) project-331.local" >> sudo tee /etc/hosts

      - name: Run npm ci for shared-modules
        run: npm ci

      - name: Build and deploy
        run: |
          skaffold build -p test
          skaffold run --port-forward --force -p test --tail &
          sleep 10
          kubectl get pods -o name --selector='waitToBeReady!=false' | xargs kubectl wait --timeout=600s --for=condition=ready
          echo "All pods ready"
          sleep 15
          bin/setup-system-test-db
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres/headless_lms_test

      - name: Setup system test environment
        run: npm ci
        working-directory: ./system-tests/

      - name: Run system tests
        run: npm run test
        working-directory: ./system-tests/
